# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJkiDt4HmAU3IqhMYODFcPlN9gQQ0DLB
"""

def tashxis(belgi):
 if belgi=="Istima":
  return "Parastemol iching"
 elif belgi == "Bosh og'rig'i":
  return "Bolnol iching"
 elif belgi == "Tish og'ri'gi":
  return "Quepen iching"
 else:
  return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiritng")
natija=tashxis(belgi)
print(natija)

def player(belgi):
  from IPython.display import Image
  if belgi=="7":
    print("player: Vini jr ")
    display(Image(filename='vini.jpg'))
    return "Vini jr"
  elif belgi == "9":
    print("player: K.Mbappe ")
    display(Image(filename='mbappe.jpg'))
    return "K. Mbappe"
  elif belgi == "5":
    print("player: Jude Bellingham ")
    display(Image(filename='mbappe.jpg'))
    return "Jude Bellingham"
  elif belgi == "11":
    print("player: Rodrigo ")
    display(Image(filename='rodri.jpg'))
    return "Rodrigo"
  elif belgi == "15":
    print("player: Arda Guler ")
    display(Image(filename='arda.jpg'))
    return "Arda Guler"
  elif belgi == "1":
    print("player: Courtois ")
    display(Image(filename='tibo.jpg'))
    return "Courtois"
  elif belgi == "2":
    print("player: Dani Carvajal ")
    display(Image(filename='dani.jpg'))
    return "Dani Carvajal"
  elif belgi == "3":
    print("player: Eder Militao ")
    display(Image(filename='mili.jpg'))
    return "Eder Militao"
  elif belgi == "4":
    return "David Alaba"
  elif belgi == "10":
    return "Luka Modrich"
  elif belgi == "6":
    return "Camavinga"
  else:
    return "No player"
belgi=input("write player's shirt number")
natija=player(belgi)
print(natija)

